teampicker/urls.py
from django.urls import path

from teampicker.views import (
    CrowdCreateView,
    CrowdDeleteView,
    CrowdDetailView,
    CrowdJoinView,
    CrowdListView,
    CrowdManageView,
    crowd_clear_view,
    crowd_join_view,
    index_view,
    team_member_delete_view,
)

app_name = "teampicker"

urlpatterns = [
    path("", index_view, name="index"),
    path("crowds/list", CrowdListView.as_view(), name="crowd-list"),
    path("crowds/manage", CrowdManageView.as_view(), name="crowd-manage"),
    path("crowds/add", CrowdCreateView.as_view(), name="crowd-add"),
    path("crowds/<str:pk>/detail", CrowdDetailView.as_view(), name="crowd-detail"),
    path("crowds/<str:pk>/clear", crowd_clear_view, name="crowd-clear"),
    path("crowds/<str:pk>/delete", CrowdDeleteView.as_view(), name="crowd-delete"),
    path("crowds/<str:pk>", CrowdJoinView.as_view(), name="crowd-join"),
    path("crowds/<str:pk>/join", crowd_join_view, name="crowd-join-team"),
    path(
        "team-member/<int:pk>/delete",
        team_member_delete_view,
        name="team-member-delete",
    ),
]

teampicker/templates/teampicker/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{% translate "teampicker" %}{% endblock %}

{% block content %}
    <br />
    {% include 'teampicker/partials/menu.html' %}
    <h2>{{ page_title }}</h2>
    {% block details %}{% endblock %}
{% endblock %}

teampicker/templates/teampicker/crowd_confirm_delete.html
{% extends 'teampicker/base.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block details %}
    <h2>Delete crowd</h2>

    <p>Are you sure you want to delete the crowd {{ object.name }}?</p>

    <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-danger">DELETE</button>
        <a class="btn btn-secondary" href="{% url 'teampicker:crowd-detail' object.pk %}" role="button">
            Cancel
        </a>
    </form>

{% endblock %}

teampicker/templates/teampicker/crowd_detail.html
{% extends 'teampicker/base.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block details %}
    <h2>Crowd Detail: {{ object.name }}</h2>

    <dl class="dl-horizontal">
        <dt>Name:</dt><dd>{{ object.name }}</dd>
        <dt>Created at:</dt><dd>{{ object.created_at }}</dd>
        <dt>Description:</dt><dd>{{ object.description|default:"-" }}</dd>
        <dt>Teams:</dt><dd>{{ object.num_teams }}</dd>
        <dt>Join URL:</dt>
        <dd>
            <a href="{{ crowd.my_teams_url }}">Link</a>&nbsp;
            <i class="far fa-copy copy-to-clipboard" title="Copy URL to clipboard" data-url="{{ crowd.my_teams_url }}"></i>
        </dd>
    </dl>

    <a class="btn btn-danger" href="{% url 'teampicker:crowd-delete' crowd.pk %}" title="Delete this crowd">Delete</a>
    <a class="btn btn-warning" href="{% url 'teampicker:crowd-clear' crowd.pk %}" title="Kick all team members">Clear</a>
    <button id="refresh-button" class="btn btn-default"><i class="fas fa-sync-alt"></i></button>

    <h4>Teams</h4>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th># Members</th>
                <th>Members</th>
            </tr>
        </thead>
        <tbody>
            {% for team in teams %}
                <tr>
                    <td>{{ team.name }}</td>
                    <td>{{ team.members.count }}</td>
                    <td>
                        <ul>
                            {% for member in team.members_sorted %}
                                <li>{{ member.name }}</li>
                            {% empty %}
                                <li class="text-warning">EMPTY</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>TOTALS</th>
                <th>{{ object.num_members }}</th>
                <th></th>
                <th></th>
            </tr>
        </tfoot>
    </table>

{% endblock %}

{% block extra_css %}
    <style>
        .dl-horizontal dt {
            text-align: left;
            width: 8em;
        }

        .dl-horizontal dd {
            margin-left: 8em;
        }
        .copy-to-clipboard:hover {
            cursor: pointer;
        }
    </style>
{% endblock %}

{% block extra_javascript %}
    <script>
        $(document).ready(function () {
            $('#refresh-button').click(function (event) {
                window.location.reload();
            });
            $('.copy-to-clipboard').click(function (event) {
                const text = event.currentTarget.getAttribute("data-url");
                navigator.clipboard.writeText(text);
            });
        });
    </script>
{% endblock %}

teampicker/templates/teampicker/crowd_form.html
{% extends 'teampicker/base.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block details %}
    <h2>Create crowd</h2>

    <form id="crowd_form" method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button id="crowd-create-save" type="submit" class="btn btn-primary">Save</button>
        <a id="crowd-create-cancel" class="btn btn-secondary" href="{% url 'teampicker:crowd-manage' %}" role="button">
            Cancel
        </a>
    </form>

{% endblock %}

teampicker/templates/teampicker/crowd_join.html
{% extends 'teampicker/base.html' %}
{% load humanize %}

{% block details %}
    <h2>Join crowd: {{ crowd.name }}</h2>

    <p>You can join a team of the <strong>{{ object.name }}</strong> crowd!</p>

    <a id="crowd-join-team" class="btn btn-success btn-lg" href="{% url 'teampicker:crowd-join-team' object.pk %}">
        Join now
    </a>

    <br>
    <br>

    {% if team_members %}
        <p>You currently have <strong>{{ num_team_members|apnumber }}</strong> team membership{{ num_team_members|pluralize }}:</p>
        <div class="rows">
            <div class="col-md-4">
                <div class="list-group">
                    {% for member in team_members %}
                        <a href="{% url 'teampicker:team-member-delete' member.pk %}" class="list-group-item" title="Leave {{ member.team.name }}">
                            {{ member.team.name }}
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <p class="text-muted">Click team to leave</p>
    {% else %}
        <p class="text-warning">You are not member of any team yet.</p>
    {% endif %}


{% endblock %}

teampicker/templates/teampicker/crowd_list.html
{% extends 'teampicker/base.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block details %}
    <h2>My crowds</h2>

    <p>You are currently a member of these crowds:</p>

    <ul>
        {% for crowd in object_list %}
            <li><a href="{{ crowd.my_teams_url }}">{{ crowd.name }}</a></li>
        {% empty %}
            <li class="text-muted">Not joined any teams yet...</li>
        {% endfor %}

    </ul>

{% endblock %}

teampicker/templates/teampicker/crowd_manage.html
{% extends 'teampicker/base.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block details %}
    <h2>Manage crowds</h2>

    <a id="crowd-create-form" class="btn btn-success" href="{% url 'teampicker:crowd-add' %}">Create crowd</a>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Created</th>
                <th>Num teams</th>
                <th>Num members</th>
            </tr>
        </thead>
        <tbody>
        {% for crowd in object_list %}
            <tr>
                <td><a href="{% url 'teampicker:crowd-detail' crowd.pk %}">{{ crowd.name }}</a></td>
                <td>{{ crowd.created_at }}</td>
                <td>{{ crowd.num_teams }}</td>
                <td>{{ crowd.num_members }}</td>
            </tr>
        {% empty %}
            <tr>
                <td class="text-muted" colspan="5">No crowds</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block extra_javascript %}
{% endblock %}