teampicker/urls.py
from django.urls import path

from teampicker.views import (
    CrowdCreateView,
    CrowdDeleteView,
    CrowdDetailView,
    CrowdJoinView,
    CrowdListView,
    CrowdManageView,
    crowd_clear_view,
    crowd_join_view,
    index_view,
    team_member_delete_view,
)

app_name = "teampicker"

urlpatterns = [
    path("", index_view, name="index"),
    path("crowds/list", CrowdListView.as_view(), name="crowd-list"),
    path("crowds/manage", CrowdManageView.as_view(), name="crowd-manage"),
    path("crowds/add", CrowdCreateView.as_view(), name="crowd-add"),
    path("crowds/<str:pk>/detail", CrowdDetailView.as_view(), name="crowd-detail"),
    path("crowds/<str:pk>/clear", crowd_clear_view, name="crowd-clear"),
    path("crowds/<str:pk>/delete", CrowdDeleteView.as_view(), name="crowd-delete"),
    path("crowds/<str:pk>", CrowdJoinView.as_view(), name="crowd-join"),
    path("crowds/<str:pk>/join", crowd_join_view, name="crowd-join-team"),
    path(
        "team-member/<int:pk>/delete",
        team_member_delete_view,
        name="team-member-delete",
    ),
]

teampicker/templates/teampicker/partials/menu.html
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'teampicker:index' %}">Team Picker</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% navactive request 'teampicker:crowd-list' %}">
                    <a href="{% url 'teampicker:crowd-list' %}">My crowds</a>
                </li>

                {% if request.resolver_match.url_name == "crowd-join" %}
                    <li class="active"><a href="#">Join crowd</a></li>
                {% endif %}

                {% if perms.freight.manage_crowds %}
                    <li class="{% navactive request 'teampicker:crowd-manage' %}">
                        <a href="{% url 'teampicker:crowd-manage' %}">Manage crowds</a>
                    </li>

                    {% if request.resolver_match.url_name == "crowd-add" %}
                        <li class="active"><a href="#">Create crowd</a></li>
                    {% endif %}

                    {% if request.resolver_match.url_name == "crowd-detail" %}
                        <li class="active"><a href="#">Crowd Detail</a></li>
                    {% endif %}

                {% endif %}
            </ul>
        </div>
    </div>
</nav>